### PR TITLE
Make the rest of common setup thread-safe (was causing rare crashes).

### PR DESCRIPTION
**Pull request by Vaelzan**
I'm not sure if absolutely all of it actually needs to be inside the DeferredWorkQueue, but I am still seeing the odd crash related to Aquaculture popup on the Valhelsia Discord's support channel every now and then (specifically pointing to the common setup phase), so I figured it was safer to wrap everything in there. Certainly, everything that I looked at appeared to lack thread safety. 

You can probably avoid the DeferredWorkQueue being required for methods in your own mod / API if you switch from HashMap to ConcurrentHashmap (eg. in FishData).

### CODE REVIEW

**Comment by GirafiStudios** [comment]
Thanks for your PR!
If you could resolve the conflicts in the PR & remove the SupressWarning you added, that would be great :)
Also if you could show an example of one of the crashes you're seeing people having.

I'll go ahead and move the API stuff to ConcurrentHashmap now.

**Comment by Vaelzan** [comment]
I have no idea why it was showing conflicts, but the warning suppression was deliberately there due to Forge erroneously deprecating DeferredWorkQueue before they added a replacement. Removed regardless.

**Comment by GirafiStudios** [comment]
Yea I know, it's just that it's not used across the entirety of the rest of the codebase - so just to keep things consistent.
Do you have an example of the crashes that's getting reported?

**Comment by Vaelzan** [comment]
Unfortunately people often send me screenshots instead of full crash reports or logs, so I don't have one in this case. I've just seen that error message enough (regarding other mods) to know that stems from something inside common setup being non-thread-safe, so every time I see it I check the code for the mods reported. 

It's possible that it doesn't need to apply to the entire contents of common setup (especially with your change to use ConcurrentHashMap), but it is also only a minimal performance hit to just run all of it on the main thread, and even then it only impacts startup.

**Comment by Vaelzan** [comment]
Example of the sort of thing I get sent pretty frequently, showing the issue (but alas not providing as much context as a full log): https://cdn.discordapp.com/attachments/553936304040050689/723173256672051301/unknown.png

It's going to take me a while to get around to submitting PRs to the other mods there too. I've already done half a dozen or so previously.

**Pull request merged**
