### PR TITLE
Ported to 1.12.2 fully

### PR DESCRIPTION
**Pull request by Sunconure11**
This commit ports the mod to 1.12.2, and fixes some minor issues with its mappings. This also implements JSON recipes for all of the items that use it. Only crafting table/crafting grid recipes have been converted to that format on 1.12, all other recipes do not use that format. Smelting still uses the same old methods, for instance.

### CODE REVIEW

**Comment by Sunconure11** [comment]
@Glassmaker Let me know when you're ready to merge this.

**Comment by TheAwesomeGem** [comment]
Waiting for the merge.

**Comment by Sunconure11** [comment]
I think that might be a bit @TheAwesomeGem. I attempted to talk to the dev several times, but he was fairly busy each time.

I'll leave this open anyways.

**Comment by GirafiStudios** [comment]
Thanks for your work @Sunconure11!
Gonna work on getting the last few things fully working in Aquaculture, before a 1.12.2 release :)

**Comment by Sunconure11** [comment]
@GirafiStudios Do you plan on implementing this? This was my gripe with aquaculture in the past. They also don't seem to extend fishing rods properly, preventing them from taking enchantments from other mods that deal with fishing rods.

https://github.com/TeamMetallurgy/Aquaculture/issues/26

**Comment by GirafiStudios** [comment]
I will talk to Shadowclaimer about your suggestions. 

JustAFewFishs API is quite bad, so no. But since vanilla basically replaces JAFF in 1.13 it might be a possibility then.

**Comment by Sunconure11** [comment]
So, what happened to the plans of picking up on biomedicts for mod support?

Side note, I have sent a request to the dev of JAFF to add support for aquaculture.

**Comment by GirafiStudios** [comment]
That is most likely going to happen for 1.13.

As for the JAFF stuff, I doubt the author wants to do that amount of work just to add support for Aquacultures fish.

**Pull request merged**
