### PR TITLE
Add sound.json for proper subtible support

### LINKED ISSUE #166: [TODO] fix sound.json
I'm leaving this here for me to do later.

### PR DESCRIPTION
**Pull request by sscards55**
Closes #166 .

### CODE REVIEW

**Comment by GirafiStudios** [comment]
Please follow Java standards with constants. Constants needs to be UPPER_CASE.
Also I think the formatting might be borked in sounds.json, seems to be mixed tabs and spaces? Could be wrong though.

**Comment by sscards55** [comment]
should I close this PR and open another or just amend this one?

**Comment by GirafiStudios** [comment]
Just amend this one ^^

**Comment by sscards55** [comment]
One thing I completely forgot about, fish don't have an ambient sound, I was thinking of using the squid swimming sound.

**Comment by sscards55** [comment]
Another thing I noticed, the note hook catching sound, should I add into the Hooks.class in the API, or somewhere else? Otherwise it would be calling mod code from the API.

**Comment by GirafiStudios** [comment]
Thanks!
Nah it's fine with the ambient sound.
Oh yea, sure go ahead with the sound in Hooks, doesn't really matter that it's in the API.

**Pull request merged**
